name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: docker-build-push
      uses: docker/build-push-action@v1
      with:
        username: zealic
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: zealic/sandbox
        tag_with_ref: true
  tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: zealic/sandbox
    steps:
    - name: show env
      run:
        env
