name: CI

on: [push]

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: docker build
      id: build
      uses: docker/build-action@v1
      with:
        repository: zealic/sandbox
        tag_with_ref: true
    - name: docker login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: docker push
      uses: docker/push-action@v1
      with:
        tag_with_ref: true
