name: CI

on: [push]

jobs:
  build-with-docker-offical:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: docker-build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository_owner }}/sandbox
        tag_with_ref: true
  build-with-docker-custom:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: run
      run: |
        docker build -t ${{ github.repository }}:custom .
        docker push ${{ github.repository }}
  build-with-docker-github:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - uses: azure/docker-login@v1
      with:
        login-server: docker.pkg.github.com
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: run
      run: |
        docker build -t docker.pkg.github.com/${{ github.repository }}/github-pkg .
        docker push docker.pkg.github.com/${{ github.repository }}/github-pkg
