name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v2
    - name: docker-build-push
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.repository_owner }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository_owner }}/sandbox
        tag_with_ref: true
    - name: run
      run: |
        docker info
        docker run -t --rm ${{ github.repository_owner }}/sandbox uname -a

  tests:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ${{ github.repository_owner }}/sandbox
    steps:
    - name: show env
      run:
        env
